/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActiveSegment { 
    id: string | null;
    pageIds?: Array<string> | null;
    segmentUsageGroupIds?: Array<string> | null;
}

