/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum ConfigType {

    Classification = 'Classification',

    Playback = 'Playback',

    Sitemap = 'Sitemap',

    Navigation = 'Navigation',

    Subscription = 'Subscription',

    General = 'General',

    Display = 'Display',

    I18n = 'I18n',

    Linear = 'Linear',

    Profile = 'Profile',

    Operations = 'Operations',

    Segments = 'Segments',

    FeatureFlags = 'FeatureFlags'
}

