/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContinueWatchingListDataExpansion } from './continueWatchingListDataExpansion';


export interface ContinueWatchingListData { 
    itemInclusions?: { [key: string]: ContinueWatchingListDataExpansion; } | null;
}

