/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface Credit { 
    name: string | null;
    path: string | null;
    role: Role;
    character?: string | null;
}



