/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DisplayConfig { 
    themes?: Array<any> | null;
    showLockIcon?: boolean;
    badgeImageBaseUrl?: string | null;
}

