/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeatureFlags { 
    mandatoryLoginEnabled?: boolean;
    oidcFeEnabled?: boolean;
    useDashPlayerOnTV?: boolean;
    mtribesEnabled?: boolean;
    npawEnabled?: boolean;
    useNewSSOOnSafari?: boolean;
    useSilentSSO?: boolean;
    disableNPAW?: boolean;
    useNewConsent?: boolean;
    pageCacheExpiration?: number;
    skipEndcredits?: boolean;
}

