/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeneralConfig { 
    websiteUrl?: string | null;
    currencyCode: string | null;
    facebookAppId?: string | null;
    maxUserRatings?: number;
    mandatorySignIn?: boolean;
    defaultTimeZone: string | null;
    itemImageTypes?: { [key: string]: string | null; } | null;
    customFields?: { [key: string]: any; } | null;
}

