/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Navigation } from './navigation';
import { GeneralConfig } from './generalConfig';
import { Playback } from './playback';
import { Rating } from './rating';
import { Segments } from './segments';
import { Internationalization } from './internationalization';
import { DisplayConfig } from './displayConfig';
import { FeatureFlags } from './featureFlags';
import { Operations } from './operations';
import { PageSummary } from './pageSummary';
import { Linear } from './linear';
import { Profile } from './profile';


export interface GetConfigResult { 
    sitemap?: Array<PageSummary> | null;
    navigation?: Navigation;
    classification?: { [key: string]: Rating; } | null;
    playback?: Playback;
    general?: GeneralConfig;
    display?: DisplayConfig;
    i18n?: Internationalization;
    linear?: Linear;
    profile?: Profile;
    operations?: Operations;
    segments?: Segments;
    featureFlags?: FeatureFlags;
}

