/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemDetails } from './itemDetails';
import { PageMetadata } from './pageMetadata';
import { PageEntry } from './pageEntry';
import { QueryablePath } from './queryablePath';
import { ItemList } from './itemList';
import { Theme } from './theme';


export interface GetPageResult { 
    id: string | null;
    title: string | null;
    path: QueryablePath;
    template: string | null;
    key?: string | null;
    isStatic?: boolean;
    isSystemPage?: boolean;
    metadata?: PageMetadata;
    entries?: Array<PageEntry> | null;
    customFields?: { [key: string]: any; } | null;
    item?: ItemDetails;
    list?: ItemList;
    themes?: Array<Theme> | null;
}

