/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemSummary } from './itemSummary';


export interface ItemRelationship { 
    key: string | null;
    items: Array<ItemSummary> | null;
}

