/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClassificationSummary } from './classificationSummary';
import { ItemRelationship } from './itemRelationship';
import { Offer } from './offer';
import { Theme } from './theme';
import { ScheduleItemDetails } from './scheduleItemDetails';


export interface ItemSummary { 
    id: string | null;
    type: string | null;
    subtype?: string | null;
    title?: string | null;
    contextualTitle?: string | null;
    shortDescription?: string | null;
    tagline?: string | null;
    classification?: ClassificationSummary;
    path?: string | null;
    watchPath?: string | null;
    scopes?: Array<string> | null;
    releaseYear?: number | null;
    episodeCount?: number | null;
    availableEpisodeCount?: number | null;
    availableSeasonCount?: number | null;
    seasonNumber?: number | null;
    episodeNumber?: number | null;
    episodeName?: string | null;
    showId?: string | null;
    showTitle?: string | null;
    seasonId?: string | null;
    channelShortCode?: string | null;
    hasClosedCaptions?: boolean | null;
    averageUserRating?: number | null;
    badge?: string | null;
    badgeBackground?: string | null;
    badgeForeground?: string | null;
    badgeImageKey?: string | null;
    genres?: Array<string> | null;
    sports?: Array<string> | null;
    duration?: number | null;
    customId?: string | null;
    eventStartDate?: string | null;
    eventEndDate?: string | null;
    firstBroadcastDate?: string | null;
    round?: string | null;
    sequenceNumber?: number | null;
    yearStart?: number | null;
    yearEnd?: number | null;
    gender?: string | null;
    country?: string | null;
    role?: string | null;
    offers?: Array<Offer> | null;
    images?: { [key: string]: string; } | null;
    themes?: Array<Theme> | null;
    customFields?: { [key: string]: any; } | null;
    relationships?: Array<ItemRelationship> | null;
    trailerWatchPaths?: Array<string> | null;
    buttonLabel?: string | null;
    liveItem?: ScheduleItemDetails;
    categories?: Array<string> | null;
    keywords?: Array<string> | null;
}

