/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { Theme } from './theme';
import { ItemSummary } from './itemSummary';
import { ListData } from './listData';
import { ListMetadata } from './listMetadata';


export interface ItemList { 
    id: string | null;
    title?: string | null;
    description?: string | null;
    shortDescription?: string | null;
    tagline?: string | null;
    path: string | null;
    itemTypes?: Array<string> | null;
    size: number;
    items: Array<ItemSummary> | null;
    listMeta?: ListMetadata;
    images?: { [key: string]: string; } | null;
    parameter?: string | null;
    paging: Pagination;
    customFields?: { [key: string]: string; } | null;
    themes?: Array<Theme> | null;
    listData?: ListData;
}

