/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChannelImage } from './channelImage';
import { CodeTextPair } from './codeTextPair';


export interface Linear { 
    viewingWindowDaysAfter?: number;
    viewingWindowDaysBefore?: number;
    scheduleCacheMaxAgeMinutes?: number;
    utcOffsetMinutes?: number;
    channelsLogo?: Array<ChannelImage> | null;
    channelGroups?: Array<CodeTextPair> | null;
    genres?: Array<CodeTextPair> | null;
}

