/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchListQueryOptions } from './searchListQueryOptions';


export interface ListMetadata { 
    isProfileList?: boolean;
    searchQuery?: SearchListQueryOptions;
}

