/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubMenuNavigationItem } from './subMenuNavigationItem';


export interface MenuGroupNavigationItem { 
    path?: string | null;
    children?: Array<SubMenuNavigationItem> | null;
    readonly depth?: number;
    label?: string | null;
}

