/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrimaryMenuNavigationItem } from './primaryMenuNavigationItem';


export interface Navigation { 
    header?: Array<PrimaryMenuNavigationItem> | null;
    footer?: PrimaryMenuNavigationItem;
    account?: PrimaryMenuNavigationItem;
    mobile?: PrimaryMenuNavigationItem;
    tv?: PrimaryMenuNavigationItem;
}

