/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvailabilityType } from './availabilityType';


export interface Offer { 
    id: string | null;
    name: string | null;
    price: number;
    startDate?: string | null;
    endDate?: string | null;
    availability: AvailabilityType;
    subscriptionCode?: string | null;
    customFields?: { [key: string]: string; } | null;
    ownership?: string | null;
    deliveryType?: string | null;
}



