/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SegmentUsageGroup } from './segmentUsageGroup';


export interface Operations { 
    segmentUsageGroups?: Array<SegmentUsageGroup> | null;
}

