/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemList } from './itemList';
import { BasicListMetadata } from './basicListMetadata';
import { Person } from './person';
import { ItemSummary } from './itemSummary';


export interface PageEntry { 
    id: string | null;
    type: string | null;
    title: string | null;
    template: string | null;
    listMeta?: BasicListMetadata;
    list?: ItemList;
    item?: ItemSummary;
    text?: string | null;
    people?: Array<Person> | null;
    customFields?: { [key: string]: any; } | null;
    images?: { [key: string]: string; } | null;
}

