/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryablePath } from './queryablePath';


export interface PageSummary { 
    id: string | null;
    title: string | null;
    path: QueryablePath;
    template: string | null;
    key?: string | null;
    isStatic?: boolean;
    isSystemPage?: boolean;
}

