/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationAuth } from './paginationAuth';
import { PaginationOptions } from './paginationOptions';


export interface Pagination { 
    next?: string | null;
    previous?: string | null;
    page: number;
    size?: number;
    total: number;
    authorization?: PaginationAuth;
    options?: PaginationOptions;
}

