/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaginationOptions { 
    pageSize?: number;
    order?: string | null;
    orderBy?: string | null;
    maxRating?: string | null;
    itemType?: string | null;
    completed?: boolean;
}

