/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Playback { 
    heartbeatFrequency?: number;
    viewEventPoints?: Array<number> | null;
    chainPlaySqueezeback?: number;
    chainPlayTimeout?: number;
    chainPlayCountdown?: number;
    liveStraightToPlayback?: boolean;
    skipButtonHideThreshold?: number;
}

