/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NavigationContent } from './navigationContent';
import { MenuGroupNavigationItem } from './menuGroupNavigationItem';


export interface PrimaryMenuNavigationItem { 
    path?: string | null;
    label?: string | null;
    content?: NavigationContent;
    children?: Array<MenuGroupNavigationItem> | null;
    readonly depth?: number;
    customFields?: { [key: string]: any; } | null;
    featured?: boolean | null;
    logoPosition?: string | null;
}

