/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Regex } from './regex';


export interface QueryablePath { 
    value?: string | null;
    regex?: Regex;
    parameters?: Array<string> | null;
}

