/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Rating { 
    images?: { [key: string]: string; } | null;
    code: string | null;
    system: string | null;
    name: string | null;
    level?: number;
    advisoryText: string | null;
}

