/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegexOptions } from './regexOptions';


export interface Regex { 
    options?: RegexOptions;
    readonly rightToLeft?: boolean;
    readonly matchTimeout?: string;
}



