/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum RegexOptions {

    NUMBER_0 = 0,

    NUMBER_1 = 1,

    NUMBER_2 = 2,

    NUMBER_4 = 4,

    NUMBER_8 = 8,

    NUMBER_16 = 16,

    NUMBER_32 = 32,

    NUMBER_64 = 64,

    NUMBER_256 = 256,

    NUMBER_512 = 512,

    NUMBER_1024 = 1024
}

