/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum Role {

    Actor = 'actor',

    Associateproducer = 'associateproducer',

    Coactor = 'coactor',

    Director = 'director',

    Executiveproducer = 'executiveproducer',

    Filminglocation = 'filminglocation',

    Guest = 'guest',

    Narrator = 'narrator',

    Other = 'other',

    Presenter = 'presenter',

    Producer = 'producer',

    Productmanager = 'productmanager',

    Thememusicby = 'thememusicby',

    Voice = 'voice',

    Writer = 'writer'
}

