/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemDetails } from './itemDetails';


export interface ScheduleItemDetails { 
    id: string | null;
    channelId: string | null;
    startDate?: string;
    endDate?: string;
    repeat?: boolean | null;
    live?: boolean | null;
    featured?: boolean | null;
    blackout?: boolean;
    item?: ItemDetails;
}

