/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchListQueryOptions { 
    term?: string | null;
    maxRating?: string | null;
    itemTypes?: string | null;
    itemSubTypes?: string | null;
    excludeItemSubTypes?: string | null;
    device?: string | null;
    sub?: string | null;
    segments?: string | null;
    ff?: string | null;
    lang?: string | null;
}

