/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubMenuNavigationItem { 
    path?: string | null;
    label: string | null;
    icon?: string | null;
    readonly depth?: number;
}

