/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThemeType } from './themeType';
import { ThemeColor } from './themeColor';


export interface Theme { 
    colors: Array<ThemeColor> | null;
    type: ThemeType;
}



