/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EpisodeSortMode } from '../model/models';
import { GetConfigResult } from '../model/models';
import { GetPageResult } from '../model/models';
import { ItemDetailExpandType } from '../model/models';
import { SeasonSelectMode } from '../model/models';
import { ServiceError } from '../model/models';
import { TextEntryFormat } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DeltatreAxisDisplayContentFrontendHostApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get the global configuration for an application. Should be called during app statup.
     * This includes things like device and playback rules, classifications, sitemap and subscriptions. You have the option to select specific configuration objects using the \&#39;include\&#39; parameter, or if unspecified, getting all configuration.
     * @endpoint get /v0.1/{tenantId}/config
     * @param tenantId 
     * @param include 
     * @param device 
     * @param sub 
     * @param segments 
     * @param lang 
     */
    getConfig(tenantId: string, include?: string, device?: string, sub?: string, segments?: string, lang?: string, extraHttpRequestParams?: any): Observable<GetConfigResult>;

    /**
     * Returns a page with the specified path.
     * If targeting the search page you must url encode the search term as a parameter using the q key. For example if your browser path looks like /search?q&#x3D;the then what you pass to this endpoint would look like /page?path&#x3D;/search%3Fq%3Dthe.
     * @endpoint get /v0.1/{tenantId}/page
     * @param tenantId 
     * @param path 
     * @param listPageSize 
     * @param listPageSizeLarge 
     * @param maxListPrefetch 
     * @param itemDetailExpand 
     * @param itemDetailSelectSeason 
     * @param itemDetailSortEpisode 
     * @param textEntryFormat 
     * @param maxRating 
     * @param device 
     * @param sub 
     * @param segments 
     * @param lang 
     * @param itemDetailIncludeFields      A comma delimited list of fields to be included in the response.      This is only applicable for fields that are not included by default.
     */
    getPage(tenantId: string, path: string, listPageSize?: number, listPageSizeLarge?: number, maxListPrefetch?: number, itemDetailExpand?: ItemDetailExpandType, itemDetailSelectSeason?: SeasonSelectMode, itemDetailSortEpisode?: EpisodeSortMode, textEntryFormat?: TextEntryFormat, maxRating?: string, device?: string, sub?: string, segments?: string, lang?: string, itemDetailIncludeFields?: string, extraHttpRequestParams?: any): Observable<GetPageResult>;

}
