/**
 * Axis Display Content FE API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { EpisodeSortMode } from '../model/episodeSortMode';
// @ts-ignore
import { GetConfigResult } from '../model/getConfigResult';
// @ts-ignore
import { GetPageResult } from '../model/getPageResult';
// @ts-ignore
import { ItemDetailExpandType } from '../model/itemDetailExpandType';
// @ts-ignore
import { SeasonSelectMode } from '../model/seasonSelectMode';
// @ts-ignore
import { ServiceError } from '../model/serviceError';
// @ts-ignore
import { TextEntryFormat } from '../model/textEntryFormat';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    DeltatreAxisDisplayContentFrontendHostApiServiceInterface
} from './deltatreAxisDisplayContentFrontendHostApi.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class DeltatreAxisDisplayContentFrontendHostApiService extends BaseService implements DeltatreAxisDisplayContentFrontendHostApiServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get the global configuration for an application. Should be called during app statup.
     * This includes things like device and playback rules, classifications, sitemap and subscriptions. You have the option to select specific configuration objects using the \&#39;include\&#39; parameter, or if unspecified, getting all configuration.
     * @endpoint get /v0.1/{tenantId}/config
     * @param tenantId 
     * @param include 
     * @param device 
     * @param sub 
     * @param segments 
     * @param lang 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getConfig(tenantId: string, include?: string, device?: string, sub?: string, segments?: string, lang?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetConfigResult>;
    public getConfig(tenantId: string, include?: string, device?: string, sub?: string, segments?: string, lang?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetConfigResult>>;
    public getConfig(tenantId: string, include?: string, device?: string, sub?: string, segments?: string, lang?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetConfigResult>>;
    public getConfig(tenantId: string, include?: string, device?: string, sub?: string, segments?: string, lang?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling getConfig.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'include',
            <any>include,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'device',
            <any>device,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sub',
            <any>sub,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'segments',
            <any>segments,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'lang',
            <any>lang,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v0.1/${this.configuration.encodeParam({name: "tenantId", value: tenantId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/config`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetConfigResult>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a page with the specified path.
     * If targeting the search page you must url encode the search term as a parameter using the q key. For example if your browser path looks like /search?q&#x3D;the then what you pass to this endpoint would look like /page?path&#x3D;/search%3Fq%3Dthe.
     * @endpoint get /v0.1/{tenantId}/page
     * @param tenantId 
     * @param path 
     * @param listPageSize 
     * @param listPageSizeLarge 
     * @param maxListPrefetch 
     * @param itemDetailExpand 
     * @param itemDetailSelectSeason 
     * @param itemDetailSortEpisode 
     * @param textEntryFormat 
     * @param maxRating 
     * @param device 
     * @param sub 
     * @param segments 
     * @param lang 
     * @param itemDetailIncludeFields      A comma delimited list of fields to be included in the response.      This is only applicable for fields that are not included by default.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getPage(tenantId: string, path: string, listPageSize?: number, listPageSizeLarge?: number, maxListPrefetch?: number, itemDetailExpand?: ItemDetailExpandType, itemDetailSelectSeason?: SeasonSelectMode, itemDetailSortEpisode?: EpisodeSortMode, textEntryFormat?: TextEntryFormat, maxRating?: string, device?: string, sub?: string, segments?: string, lang?: string, itemDetailIncludeFields?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetPageResult>;
    public getPage(tenantId: string, path: string, listPageSize?: number, listPageSizeLarge?: number, maxListPrefetch?: number, itemDetailExpand?: ItemDetailExpandType, itemDetailSelectSeason?: SeasonSelectMode, itemDetailSortEpisode?: EpisodeSortMode, textEntryFormat?: TextEntryFormat, maxRating?: string, device?: string, sub?: string, segments?: string, lang?: string, itemDetailIncludeFields?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetPageResult>>;
    public getPage(tenantId: string, path: string, listPageSize?: number, listPageSizeLarge?: number, maxListPrefetch?: number, itemDetailExpand?: ItemDetailExpandType, itemDetailSelectSeason?: SeasonSelectMode, itemDetailSortEpisode?: EpisodeSortMode, textEntryFormat?: TextEntryFormat, maxRating?: string, device?: string, sub?: string, segments?: string, lang?: string, itemDetailIncludeFields?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetPageResult>>;
    public getPage(tenantId: string, path: string, listPageSize?: number, listPageSizeLarge?: number, maxListPrefetch?: number, itemDetailExpand?: ItemDetailExpandType, itemDetailSelectSeason?: SeasonSelectMode, itemDetailSortEpisode?: EpisodeSortMode, textEntryFormat?: TextEntryFormat, maxRating?: string, device?: string, sub?: string, segments?: string, lang?: string, itemDetailIncludeFields?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (tenantId === null || tenantId === undefined) {
            throw new Error('Required parameter tenantId was null or undefined when calling getPage.');
        }
        if (path === null || path === undefined) {
            throw new Error('Required parameter path was null or undefined when calling getPage.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'path',
            <any>path,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'list_page_size',
            <any>listPageSize,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'list_page_size_large',
            <any>listPageSizeLarge,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'max_list_prefetch',
            <any>maxListPrefetch,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'item_detail_expand',
            <any>itemDetailExpand,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'item_detail_select_season',
            <any>itemDetailSelectSeason,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'item_detail_sort_episode',
            <any>itemDetailSortEpisode,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'text_entry_format',
            <any>textEntryFormat,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'max_rating',
            <any>maxRating,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'device',
            <any>device,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'sub',
            <any>sub,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'segments',
            <any>segments,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'lang',
            <any>lang,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'item_detail_include_fields',
            <any>itemDetailIncludeFields,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v0.1/${this.configuration.encodeParam({name: "tenantId", value: tenantId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/page`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetPageResult>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
