/**
 * Drtv Videos Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssetMetadata { 
    assetUrl: string;
    assetType?: string | null;
    assetId?: string | null;
    watchUrl?: string | null;
}

