/**
 * Drtv Videos Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceErrorResponse { 
    error?: string | null;
    error_description?: string | null;
    error_uri?: string | null;
    error_code?: number | null;
}

