/**
 * Drtv Videos Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MediaFile } from '../model/models';
import { ServiceError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AccountApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * GetItemMediaFiles
     * 
     * @endpoint get /api/account/items/{id}/videos
     * @param id 
     * @param delivery 
     * @param resolution 
     * @param device 
     * @param geoLocation 
     * @param isLive2Vod 
     * @param formats 
     * @param sub 
     * @param segments 
     * @param fF 
     * @param lang 
     * @param apiVersion 
     */
    apiAccountItemsIdVideosGet(id: string, delivery: Array<string>, resolution: string, device: string, geoLocation: string, isLive2Vod?: boolean, formats?: Array<string>, sub?: string, segments?: Array<string>, fF?: Array<string>, lang?: string, apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<MediaFile>>;

}
